kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  labels:
    app: mongodb
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
