apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      run: webserver
  replicas: 2
  template:
    metadata:
      labels:
        run: webserver
    spec:
      containers:
        - name: webserver
          image: webserver:registry
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
            ##  protocol: TCP

